// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package events

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// EventsClient is the client API for Events service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventsClient interface {
	EventUpdate(ctx context.Context, in *ServerSpec, opts ...grpc.CallOption) (Events_EventUpdateClient, error)
}

type eventsClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsClient(cc grpc.ClientConnInterface) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) EventUpdate(ctx context.Context, in *ServerSpec, opts ...grpc.CallOption) (Events_EventUpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Events_serviceDesc.Streams[0], "/events.events/EventUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventsEventUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Events_EventUpdateClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type eventsEventUpdateClient struct {
	grpc.ClientStream
}

func (x *eventsEventUpdateClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventsServer is the server API for Events service.
// All implementations must embed UnimplementedEventsServer
// for forward compatibility
type EventsServer interface {
	EventUpdate(*ServerSpec, Events_EventUpdateServer) error
	mustEmbedUnimplementedEventsServer()
}

// UnimplementedEventsServer must be embedded to have forward compatible implementations.
type UnimplementedEventsServer struct {
}

func (UnimplementedEventsServer) EventUpdate(*ServerSpec, Events_EventUpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method EventUpdate not implemented")
}
func (UnimplementedEventsServer) mustEmbedUnimplementedEventsServer() {}

// UnsafeEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsServer will
// result in compilation errors.
type UnsafeEventsServer interface {
	mustEmbedUnimplementedEventsServer()
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_EventUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerSpec)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventsServer).EventUpdate(m, &eventsEventUpdateServer{stream})
}

type Events_EventUpdateServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type eventsEventUpdateServer struct {
	grpc.ServerStream
}

func (x *eventsEventUpdateServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "events.events",
	HandlerType: (*EventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventUpdate",
			Handler:       _Events_EventUpdate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/grpc/events.proto",
}
