package api

import (
	"net/http"

	"gitlab.com/project-emco/core/emco-base/src/orchestrator/pkg/infra/apierror"
)

var apiErrors = []apierror.APIError{

	{ID: "Cluster reference already exists", Message: "Cluster reference already exists", Status: http.StatusConflict},
	{ID: "Cluster reference not found", Message: "Cluster reference not found", Status: http.StatusNotFound},
	{ID: "Cluster Reference mismatch", Message: "Cluster Reference mismatch", Status: http.StatusConflict},
	{ID: "No Cluster References associated", Message: "No Cluster References associated", Status: http.StatusBadRequest},
	{ID: "Error getting app context status", Message: "Error getting app context status", Status: http.StatusInternalServerError},
	{ID: "Cluster References cannot be added", Message: "Cluster References cannot be added/removed unless the Logical Cloud is not instantiated", Status: http.StatusConflict},
	{ID: "Can't remove Cluster Reference: the Logical Cloud is being terminated", Message: "Can't remove Cluster Reference: the Logical Cloud is being terminated", Status: http.StatusConflict},
	{ID: "Can't remove Cluster Reference: the Logical Cloud is instantiated, please terminate first", Message: "Can't remove Cluster Reference: the Logical Cloud is instantiated, please terminate first", Status: http.StatusConflict},
	{ID: "Can't remove Cluster Reference: the Logical Cloud is instantiating, please wait and then terminate.", Message: "Can't remove Cluster Reference: the Logical Cloud is instantiating, please wait and then terminate.", Status: http.StatusConflict},
	{ID: "Can't remove Cluster Reference: the Logical Cloud has failed instantiating, for safety please terminate and try again", Message: "Can't remove Cluster Reference: the Logical Cloud has failed instantiating, for safety please terminate and try again", Status: http.StatusConflict},
	{ID: "Failure removing Cluster Reference: the Logical Cloud isn't in an expected status so not taking any action.", Message: "Failure removing Cluster Reference: the Logical Cloud isn't in an expected status so not taking any action.", Status: http.StatusConflict},
	{ID: "The cluster doesn't contain status, please check if all services are up and running", Message: "The cluster doesn't contain status, please check if all services are up and running", Status: http.StatusConflict},
	{ID: "An error occurred while reading the cluster status", Message: "An error occurred while reading the cluster status", Status: http.StatusInternalServerError},
	{ID: "An error occurred while parsing the cluster status", Message: "An error occurred while parsing the cluster status", Status: http.StatusInternalServerError},
	{ID: "A status for the CSR hasn't been returned", Message: "A status for the CSR hasn't been returned", Status: http.StatusInternalServerError},
	{ID: "Error getting logical cloud context", Message: "Error getting logical cloud context", Status: http.StatusInternalServerError},
	{ID: "Logical Cloud hasn't been instantiated", Message: "Logical Cloud hasn't been instantiated", Status: http.StatusConflict},
	{ID: "Error getting logical cloud", Message: "Error getting logical cloud", Status: http.StatusInternalServerError},
	{ID: "Error getting private key from logical cloud", Message: "Error getting private key from logical cloud", Status: http.StatusInternalServerError},
	{ID: "Error getting cluster", Message: "Error getting cluster", Status: http.StatusInternalServerError},
	{ID: "Key Value already exists", Message: "Key Value already exists", Status: http.StatusConflict},
	{ID: "Key Value not found", Message: "Key Value not found", Status: http.StatusNotFound},
	{ID: "KV pair name mismatch", Message: "KV pair name mismatch", Status: http.StatusConflict},
	{ID: "Logical Cloud already exists", Message: "Logical Cloud already exists", Status: http.StatusConflict},
	{ID: "Logical Cloud not found", Message: "Logical Cloud not found", Status: http.StatusNotFound},
	{ID: "Logical Cloud name mismatch", Message: "Logical Cloud name mismatch", Status: http.StatusConflict},
	{ID: "The Logical Cloud can't be deleted yet, it is being terminated", Message: "The Logical Cloud can't be deleted yet, it is being terminated", Status: http.StatusConflict},
	{ID: "The Logical Cloud is instantiated, please terminate first", Message: "The Logical Cloud is instantiated, please terminate first", Status: http.StatusConflict},
	{ID: "The Logical Cloud is instantiating, please wait and then terminate", Message: "The Logical Cloud is instantiating, please wait and then terminate", Status: http.StatusConflict},
	{ID: "The Logical Cloud has failed instantiating, for safety please terminate and try again", Message: "The Logical Cloud has failed instantiating, for safety please terminate and try again", Status: http.StatusConflict},
	{ID: "Error deleting AppContext", Message: "Error deleting AppContext CompositeApp Logical Cloud", Status: http.StatusInternalServerError},
	{ID: "Logical Cloud AppContext not found", Message: "Logical Cloud AppContext not found", Status: http.StatusNotFound},
	{ID: "Project not found", Message: "Project not found", Status: http.StatusNotFound},
	{ID: "Cluster Quotas not allowed for Logical Cloud Level 0", Message: "Cluster Quotas not allowed for Logical Cloud Level 0", Status: http.StatusBadRequest},
	{ID: "Quota already exists", Message: "Quota already exists", Status: http.StatusConflict},
	{ID: "Cluster Quota not found", Message: "Cluster Quota not found", Status: http.StatusNotFound},
	{ID: "Quota name mismatch", Message: "Quota name mismatch", Status: http.StatusConflict},
	{ID: "User Permission already exists", Message: "User Permission already exists", Status: http.StatusConflict},
	{ID: "User Permission not found", Message: "User Permission not found", Status: http.StatusNotFound},
	{ID: "Permission name mismatch", Message: "Permission name mismatch", Status: http.StatusConflict},
	{ID: "Error when deleting Logical Cloud", Message: "Error when deleting Logical Cloud", Status: http.StatusInternalServerError},
	{ID: "The Logical Cloud can't be re-instantiated yet, it is being terminated", Message: "The Logical Cloud can't be re-instantiated yet, it is being terminated", Status: http.StatusConflict},
	{ID: "The Logical Cloud is already instantiated", Message: "The Logical Cloud is already instantiated", Status: http.StatusConflict},
	{ID: "The Logical Cloud is already instantiating", Message: "The Logical Cloud is already instantiating", Status: http.StatusConflict},
	{ID: "The Logical Cloud has failed instantiating before, please terminate and try again", Message: "The Logical Cloud has failed instantiating before, please terminate and try again", Status: http.StatusConflict},
	{ID: "The Logical Cloud has failed terminating, please try to terminate again or delete the Logical Cloud", Message: "The Logical Cloud has failed terminating, please try to terminate again or delete the Logical Cloud", Status: http.StatusConflict},
	{ID: "Logical cloud don't all share the same namespace", Message: "The clusters associated to this L0 logical cloud don't all share the same namespace name", Status: http.StatusConflict},
	{ID: "Level-1 Logical Clouds require a Quota", Message: "Level-1 Logical Clouds require a Quota to be associated first", Status: http.StatusConflict},
	{ID: "Level-1 Logical Clouds require a User Permission", Message: "Level-1 Logical Clouds require a User Permission assigned to its primary namespace", Status: http.StatusConflict},
	{ID: "The cluster provided as reference does not exist", Message: "The cluster provided as reference does not exist", Status: http.StatusConflict},
	{ID: "The Logical Cloud is not instantiated", Message: "The Logical Cloud is not instantiated", Status: http.StatusConflict},
	{ID: "The Logical Cloud has already been terminated", Message: "The Logical Cloud has already been terminated", Status: http.StatusConflict},
	{ID: "The Logical Cloud is already being terminated", Message: "The Logical Cloud is already being terminated", Status: http.StatusConflict},
	{ID: "The Logical Cloud is still instantiating", Message: "The Logical Cloud is still instantiating", Status: http.StatusConflict},
}
