# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

#################################################################
# Global configuration defaults.
#################################################################
global:
  nodePortPrefixExt: 304
  persistence: {}
#################################################################
# Application configuration defaults.
#################################################################
# application image
# repository: registry.gitlab.com/project-emco/core/emco-base/ # uncomment to override default/inherited repository
# emcoTag: latest # uncomment to override default/inherited emcoTag
image: emco-dcm

pullPolicy: Always
command: "./dcm"
args: ""
workingDir: /opt/emco/dcm

# flag to mount mongo db secret
mountMongoSecret: true

# flag to enable debugging - application support required
debugEnabled: true

# application configuration is via config files

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 30
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 10
  periodSeconds: 30

service:
  type: NodePort
  name: dcm
  portName: dcm-service
  internalPort: 9077
  externalPort: 9077
  nodePort: 77

serviceInternal:
  type: NodePort
  name: dcm
  portName: dcm-status
  internalPort: 9078
  externalPort: 9078
  nodePort: 78

ingress:
  enabled: false

# Configure resource requests and limits
flavor: large
resources:
  small:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 10Mi
  large:
    limits:
      cpu: 400m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
  unlimited: {}

podAnnotations:
  # The metrics use the same port as the service
  prometheus.io/path: /metrics
  prometheus.io/port: "9077"
  prometheus.io/scrape: "true"
