// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2022 Intel Corporation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.11.4
// source: contextupdate.proto

package contextupdate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event type for the event
type EventType int32

const (
	EventType_INSTANTIATE EventType = 0
	EventType_TERMINATE   EventType = 1
	EventType_UPDATE      EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "INSTANTIATE",
		1: "TERMINATE",
		2: "UPDATE",
	}
	EventType_value = map[string]int32{
		"INSTANTIATE": 0,
		"TERMINATE":   1,
		"UPDATE":      2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_contextupdate_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_contextupdate_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_contextupdate_proto_rawDescGZIP(), []int{0}
}

type ContextUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AppContextId for the Request
	AppContext string `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	IntentName string `protobuf:"bytes,2,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"`
	// Only populated if update/migrate case
	UpdateFromAppContext string `protobuf:"bytes,3,opt,name=update_from_appContext,json=updateFromAppContext,proto3" json:"update_from_appContext,omitempty"`
}

func (x *ContextUpdateRequest) Reset() {
	*x = ContextUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contextupdate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContextUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUpdateRequest) ProtoMessage() {}

func (x *ContextUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextupdate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUpdateRequest.ProtoReflect.Descriptor instead.
func (*ContextUpdateRequest) Descriptor() ([]byte, []int) {
	return file_contextupdate_proto_rawDescGZIP(), []int{0}
}

func (x *ContextUpdateRequest) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *ContextUpdateRequest) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

func (x *ContextUpdateRequest) GetUpdateFromAppContext() string {
	if x != nil {
		return x.UpdateFromAppContext
	}
	return ""
}

type ContextUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContextUpdated       bool   `protobuf:"varint,1,opt,name=app_context_updated,json=appContextUpdated,proto3" json:"app_context_updated,omitempty"`
	AppContextUpdateMessage string `protobuf:"bytes,2,opt,name=app_context_update_message,json=appContextUpdateMessage,proto3" json:"app_context_update_message,omitempty"`
}

func (x *ContextUpdateResponse) Reset() {
	*x = ContextUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contextupdate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContextUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUpdateResponse) ProtoMessage() {}

func (x *ContextUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextupdate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUpdateResponse.ProtoReflect.Descriptor instead.
func (*ContextUpdateResponse) Descriptor() ([]byte, []int) {
	return file_contextupdate_proto_rawDescGZIP(), []int{1}
}

func (x *ContextUpdateResponse) GetAppContextUpdated() bool {
	if x != nil {
		return x.AppContextUpdated
	}
	return false
}

func (x *ContextUpdateResponse) GetAppContextUpdateMessage() string {
	if x != nil {
		return x.AppContextUpdateMessage
	}
	return ""
}

type TerminateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AppContextId for the Request
	AppContext string `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contextupdate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextupdate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_contextupdate_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateRequest) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

type TerminateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppContextTerminated        bool   `protobuf:"varint,1,opt,name=app_context_terminated,json=appContextTerminated,proto3" json:"app_context_terminated,omitempty"`
	AppContextTerminatedMessage string `protobuf:"bytes,2,opt,name=app_context_terminated_message,json=appContextTerminatedMessage,proto3" json:"app_context_terminated_message,omitempty"`
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contextupdate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextupdate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_contextupdate_proto_rawDescGZIP(), []int{3}
}

func (x *TerminateResponse) GetAppContextTerminated() bool {
	if x != nil {
		return x.AppContextTerminated
	}
	return false
}

func (x *TerminateResponse) GetAppContextTerminatedMessage() string {
	if x != nil {
		return x.AppContextTerminatedMessage
	}
	return ""
}

type PostEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AppContextId for the Request
	AppContext string    `protobuf:"bytes,1,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"`
	EventType  EventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=EventType" json:"event_type,omitempty"`
}

func (x *PostEventRequest) Reset() {
	*x = PostEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contextupdate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostEventRequest) ProtoMessage() {}

func (x *PostEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextupdate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostEventRequest.ProtoReflect.Descriptor instead.
func (*PostEventRequest) Descriptor() ([]byte, []int) {
	return file_contextupdate_proto_rawDescGZIP(), []int{4}
}

func (x *PostEventRequest) GetAppContext() string {
	if x != nil {
		return x.AppContext
	}
	return ""
}

func (x *PostEventRequest) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_INSTANTIATE
}

type PostEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success          bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PostEventMessage string `protobuf:"bytes,2,opt,name=post_event_message,json=postEventMessage,proto3" json:"post_event_message,omitempty"`
}

func (x *PostEventResponse) Reset() {
	*x = PostEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contextupdate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostEventResponse) ProtoMessage() {}

func (x *PostEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contextupdate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostEventResponse.ProtoReflect.Descriptor instead.
func (*PostEventResponse) Descriptor() ([]byte, []int) {
	return file_contextupdate_proto_rawDescGZIP(), []int{5}
}

func (x *PostEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PostEventResponse) GetPostEventMessage() string {
	if x != nil {
		return x.PostEventMessage
	}
	return ""
}

var File_contextupdate_proto protoreflect.FileDescriptor

var file_contextupdate_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x34, 0x0a, 0x16, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x14, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x70, 0x70, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x13, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61,
	0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x3b, 0x0a, 0x1a, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x33, 0x0a,
	0x10, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x11, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x61, 0x70, 0x70, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x12, 0x43,
	0x0a, 0x1e, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1b, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x5e, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70,
	0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x29, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x5b, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x70, 0x6f, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2a, 0x37, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x54, 0x49, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x32, 0xca, 0x01, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x43, 0x0a, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x15, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x13, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x11, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x54, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x34, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_contextupdate_proto_rawDescOnce sync.Once
	file_contextupdate_proto_rawDescData = file_contextupdate_proto_rawDesc
)

func file_contextupdate_proto_rawDescGZIP() []byte {
	file_contextupdate_proto_rawDescOnce.Do(func() {
		file_contextupdate_proto_rawDescData = protoimpl.X.CompressGZIP(file_contextupdate_proto_rawDescData)
	})
	return file_contextupdate_proto_rawDescData
}

var file_contextupdate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contextupdate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contextupdate_proto_goTypes = []interface{}{
	(EventType)(0),                // 0: EventType
	(*ContextUpdateRequest)(nil),  // 1: ContextUpdateRequest
	(*ContextUpdateResponse)(nil), // 2: ContextUpdateResponse
	(*TerminateRequest)(nil),      // 3: TerminateRequest
	(*TerminateResponse)(nil),     // 4: TerminateResponse
	(*PostEventRequest)(nil),      // 5: PostEventRequest
	(*PostEventResponse)(nil),     // 6: PostEventResponse
}
var file_contextupdate_proto_depIdxs = []int32{
	0, // 0: PostEventRequest.event_type:type_name -> EventType
	1, // 1: contextupdate.UpdateAppContext:input_type -> ContextUpdateRequest
	3, // 2: contextupdate.TerminateAppContext:input_type -> TerminateRequest
	5, // 3: contextupdate.PostEvent:input_type -> PostEventRequest
	2, // 4: contextupdate.UpdateAppContext:output_type -> ContextUpdateResponse
	4, // 5: contextupdate.TerminateAppContext:output_type -> TerminateResponse
	6, // 6: contextupdate.PostEvent:output_type -> PostEventResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contextupdate_proto_init() }
func file_contextupdate_proto_init() {
	if File_contextupdate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contextupdate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContextUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contextupdate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContextUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contextupdate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contextupdate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contextupdate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contextupdate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contextupdate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contextupdate_proto_goTypes,
		DependencyIndexes: file_contextupdate_proto_depIdxs,
		EnumInfos:         file_contextupdate_proto_enumTypes,
		MessageInfos:      file_contextupdate_proto_msgTypes,
	}.Build()
	File_contextupdate_proto = out.File
	file_contextupdate_proto_rawDesc = nil
	file_contextupdate_proto_goTypes = nil
	file_contextupdate_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ContextupdateClient is the client API for Contextupdate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContextupdateClient interface {
	// Instantiation
	UpdateAppContext(ctx context.Context, in *ContextUpdateRequest, opts ...grpc.CallOption) (*ContextUpdateResponse, error)
	// Termination
	TerminateAppContext(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
	// Post Instantiation, Update and Terminate event
	PostEvent(ctx context.Context, in *PostEventRequest, opts ...grpc.CallOption) (*PostEventResponse, error)
}

type contextupdateClient struct {
	cc grpc.ClientConnInterface
}

func NewContextupdateClient(cc grpc.ClientConnInterface) ContextupdateClient {
	return &contextupdateClient{cc}
}

func (c *contextupdateClient) UpdateAppContext(ctx context.Context, in *ContextUpdateRequest, opts ...grpc.CallOption) (*ContextUpdateResponse, error) {
	out := new(ContextUpdateResponse)
	err := c.cc.Invoke(ctx, "/contextupdate/UpdateAppContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextupdateClient) TerminateAppContext(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, "/contextupdate/TerminateAppContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextupdateClient) PostEvent(ctx context.Context, in *PostEventRequest, opts ...grpc.CallOption) (*PostEventResponse, error) {
	out := new(PostEventResponse)
	err := c.cc.Invoke(ctx, "/contextupdate/PostEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContextupdateServer is the server API for Contextupdate service.
type ContextupdateServer interface {
	// Instantiation
	UpdateAppContext(context.Context, *ContextUpdateRequest) (*ContextUpdateResponse, error)
	// Termination
	TerminateAppContext(context.Context, *TerminateRequest) (*TerminateResponse, error)
	// Post Instantiation, Update and Terminate event
	PostEvent(context.Context, *PostEventRequest) (*PostEventResponse, error)
}

// UnimplementedContextupdateServer can be embedded to have forward compatible implementations.
type UnimplementedContextupdateServer struct {
}

func (*UnimplementedContextupdateServer) UpdateAppContext(context.Context, *ContextUpdateRequest) (*ContextUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAppContext not implemented")
}
func (*UnimplementedContextupdateServer) TerminateAppContext(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateAppContext not implemented")
}
func (*UnimplementedContextupdateServer) PostEvent(context.Context, *PostEventRequest) (*PostEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostEvent not implemented")
}

func RegisterContextupdateServer(s *grpc.Server, srv ContextupdateServer) {
	s.RegisterService(&_Contextupdate_serviceDesc, srv)
}

func _Contextupdate_UpdateAppContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextupdateServer).UpdateAppContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contextupdate/UpdateAppContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextupdateServer).UpdateAppContext(ctx, req.(*ContextUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contextupdate_TerminateAppContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextupdateServer).TerminateAppContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contextupdate/TerminateAppContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextupdateServer).TerminateAppContext(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contextupdate_PostEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextupdateServer).PostEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contextupdate/PostEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextupdateServer).PostEvent(ctx, req.(*PostEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contextupdate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contextupdate",
	HandlerType: (*ContextupdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAppContext",
			Handler:    _Contextupdate_UpdateAppContext_Handler,
		},
		{
			MethodName: "TerminateAppContext",
			Handler:    _Contextupdate_TerminateAppContext_Handler,
		},
		{
			MethodName: "PostEvent",
			Handler:    _Contextupdate_PostEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contextupdate.proto",
}
