apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-localzone-upf-config
  labels:
    epc-mode: localzone-upf
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log

    upf:
        pfcp:
           dev: {{ .Values.k8s.interface }}
        gtpu:
           dev: {{ .Values.k8s.interface }}
        subnet:
          - addr: 10.45.1.1/24
            dnn: {{ .Values.localzoneDnn }}
