# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: 339807939780.dkr.ecr.us-west-2.amazonaws.com/open5gs-aio
    pullPolicy: IfNotPresent
    tag: "latest"

ueransim:
   repository: 339807939780.dkr.ecr.us-west-2.amazonaws.com/ueransim
   pullPolicy: IfNotPresent
   tag: "latest"   
   ue1:
     imsi: "208930000000031"
     imei: "356938035643803"
     imeiSv: "4370816125816151"
     op: "63bfa50ee6523365ff14c1f45f88737d"
     secKey: "0C0A34601D4F07677303652C0462535B"
   ue2:
     imsi: "208930000000032"
     imei: "356938035643803"
     imeiSv: "4370816125816151"
     op: "63bfa50ee6523365ff14c1f45f88737d"
     secKey: "0C0A34601D4F07677303652C0462535B"         

RegionNodeSelector:
    location: region
LZnodeSelector:
    location: localzone

k8swait:
   repository: 339807939780.dkr.ecr.us-west-2.amazonaws.com/amf-check
   pullPolicy: IfNotPresent
   tag: "latest"
   serviceHost: aeb8499ba3b6c404d982c5acbf7ecdd2-1d55a8c91547f799.elb.us-west-2.amazonaws.com
   servicePort: 30080

webui:
  image:
    repository: 339807939780.dkr.ecr.us-west-2.amazonaws.com/open5gs-webui
    pullPolicy: IfNotPresent
    tag: "latest"
  ingress:
    enabled: false
    ## Ingress annotations done as key:value pairs
    ## For a full list of possible ingress annotations, please see
    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
    ##
    ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
    # annotations:
    #   kubernetes.io/ingress.class: nginx

    hosts:
      - name: open5gs-epc.local
        paths: ["/"]
        ## Set this to true in order to enable TLS on the ingress record
        tls: false

        ## Optionally specify the TLS hosts for the ingress record
        ## Useful when the Ingress controller supports www-redirection
        ## If not specified, the above host name will be used
        # tlsHosts:
        # - www.open5gs-epc.local
        # - open5gs-epc.local

        ## If TLS is set to true, you can declare what secret will store the key/certificate for TLS
        # tlsSecret: open5gs-epc.local-tls    

regionDnn: reginternet
localzoneDnn: lzinternet

config:  
  mcc: 208
  mnc: 93
  tac: 7
  sst: 1
  sd: 1
  address: aeb8499ba3b6c404d982c5acbf7ecdd2-1d55a8c91547f799.elb.us-west-2.amazonaws.com

# Primary/Native kubernetes interface
k8s:
 interface: eth0