apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pcf
  labels:
    epc-mode: pcf
spec:
  selector:
    epc-mode: pcf
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pcf-deployment
  labels:
    epc-mode: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: pcf
  template:
    metadata:
      labels:
        epc-mode: pcf
    spec:
      serviceAccountName: {{ .Release.Name }}-k8s-wait-for    
      {{- if .Values.RegionNodeSelector}}
      nodeSelector: {{- .Values.RegionNodeSelector | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
      - name: wait-for-gnb
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lepc-mode=nrf"
      - name: wait-for-mongo
        image: "{{ .Values.k8swait.repository }}:{{ .Values.k8swait.tag }}"
        imagePullPolicy: {{ .Values.k8swait.pullPolicy }}
        args:
          - "pod"
          - "-lapp=open5gs-mongodb"          
      containers:
        - name: pcf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["open5gs-pcfd", "-c", "/open5gs/config-map/pcf.yaml"]
          volumeMounts:
          - name: {{ .Release.Name }}-pcf-config
            mountPath: /open5gs/config-map/pcf.yaml
            subPath: "pcf.yaml"          
      volumes:
        - name: {{ .Release.Name }}-pcf-config
          configMap:
            name: {{ .Release.Name }}-pcf-config         
