apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-smf-config
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    parameter:
        no_ipv6: true

    smf:
        sbi:     
        - addr: 0.0.0.0
          advertise: {{ .Release.Name }}-smf
        pfcp:
           dev: {{ .Values.k8s.interface }}
        gtpc:
          dev: {{ .Values.k8s.interface }}
        gtpu:
          dev: {{ .Values.k8s.interface }}    
        subnet:
         - addr: 10.45.0.1/24
           dnn: {{ .Values.regionDnn }}
         - addr: 10.45.1.1/24
           dnn: {{ .Values.localzoneDnn }}
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400

    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf 

    upf:
      pfcp:
        - name: {{ .Release.Name }}-localzone-upf-svc
          dnn: {{ .Values.localzoneDnn }}
        - name: {{ .Release.Name }}-region-upf-svc
          dnn: {{ .Values.regionDnn }}
