full_api_test_list = [('project', 'test_postProjects.py', 'test_postProjects.json'),
('project','test_postProjects.py', 'negative_error_codes/test_postProjectsNeg400.json'),
('project', 'test_postProjects.py', 'negative_error_codes/test_postProjectsNeg404.json'),
('project', 'test_postProjects.py', 'negative_error_codes/test_postProjectsNeg409.json'),
('project', 'test_postProjectsNeg422.py', 'negative_error_codes/test_postProjectsNeg422.json'),
('project', 'test_getProjects.py', 'test_getProjects.json'),
('project', 'test_getProjects.py', 'negative_error_codes/test_getProjectsNeg404.json'),
('project', 'test_getProjectsByName.py', 'test_getProjectsByName.json'),
('project', 'test_getProjectsByName.py', 'negative_error_codes/test_getProjectsByNameNeg404.json'),
('controller_registration', 'test_postControllers.py', 'test_postControllerRegistration.json'),
('controller_registration', 'test_postControllers.py', 'test_postTrafficControllerRegistration.json'),
('controller_registration', 'test_getControllers.py', 'test_getControllerRegistrations.json'),
('controller_registration', 'test_getControllersByName.py', 'test_getControllerRegistrationByName.json  '),
('controller_registration', 'test_getControllersByName.py', 'test_getTrafficControllerRegistrationByName.json'),
('dtc_controllers', 'test_postDtcControllers.py', 'test_postDtcControllers.json'),
('cluster_provider', 'test_postClusterProvider.py', 'test_postClusterProvider.json'),
('cluster_provider', 'test_postClusterProvider.py', 'test_postClusterProviderNeg400.json'),
('cluster_provider', 'test_postClusterProvider.py', 'test_postClusterProviderNeg404NoClusterProvider.json'),
('cluster_provider', 'test_postClusterProvider.py', 'test_postClusterProviderNeg409.json'),
('cluster_provider', 'test_postClusterProviderNeg422.py', 'test_postClusterProviderNeg422.json'),
('cluster_provider', 'test_getClusterProvider.py', 'test_getClusterProvider.json'),
('cluster_provider', 'test_getClusterProvider.py', 'test_getClusterProviderNeg404.json'),
('cluster_provider', 'test_getClusterProviderByName.py', 'test_getClusterProviderByName.json'),
('cluster_provider', 'test_getClusterProviderByName.py', 'test_getClusterProviderByNameNeg404.json'),
('clusters', 'test_postCluster.py', 'test_postCluster.json'),
('clusters', 'test_postCluster.py', 'negative_error_codes/test_postClusterNeg400.json'),
('clusters', 'test_postCluster.py', 'negative_error_codes/test_postClusterNeg404.json'),
('clusters', 'test_postCluster.py', 'negative_error_codes/test_postClusterNeg409.json'),
('clusters', 'test_postClusterNeg422.py', 'negative_error_codes/test_postClusterNeg422.json'),
('clusters', 'test_getClusters.py', 'test_getClusters.json'),
('clusters', 'test_getClusters.py', 'negative_error_codes/test_getClustersNeg404.json'),
('clusters', 'test_getClusterByName.py', 'test_getClusterByName.json'),
('clusters', 'test_getClusterByName.py', 'negative_error_codes/test_getClusterByNameNeg404.json'),
('clusters', 'test_postClusterLabel.py', 'test_postClusterLabel.json'),
('clusters', 'test_postClusterLabel.py', 'negative_error_codes/test_postClusterLabelNeg400.json'),
('clusters', 'test_postClusterLabel.py', 'negative_error_codes/test_postClusterLabelNeg404.json'),
('clusters', 'test_postClusterLabel.py', 'negative_error_codes/test_postClusterLabelNeg409.json'),
('clusters', 'test_postClusterLabelNeg422.py', 'negative_error_codes/test_postClusterLabelNeg422.json'),
('clusters', 'test_getClusterLabels.py', 'test_getClusterLabels.json'),
('clusters', 'test_getClusterLabels.py', 'negative_error_codes/test_getClusterLabelsNeg404.json'),
('clusters', 'test_getClusterLabelByName.py', 'test_getClusterLabelByName.json'),
('clusters', 'test_getClusterLabelByName.py', 'negative_error_codes/test_getClusterLabelByNameNeg404.json'),
('clusters', 'test_getClustersForLabel.py', 'test_getClustersForLabel.json'),
('clusters', 'test_getClustersForLabel.py', 'negative_error_codes/test_getClustersForLabelNeg404.json'),
('clusters', 'test_postClusterKVPair.py', 'test_postClusterKVPair.json'),
('clusters', 'test_postClusterKVPair.py', 'negative_error_codes/test_postClusterKVPairNeg400.json'),
('clusters', 'test_postClusterKVPair.py', 'negative_error_codes/test_postClusterKVPairNeg404.json'),
('clusters', 'test_postClusterKVPair.py', 'negative_error_codes/test_postClusterKVPairNeg409.json'),
('clusters', 'test_postClusterKVPairNeg422.py', 'negative_error_codes/test_postClusterKVPairNeg422.json'),
('clusters', 'test_getClusterKVPairs.py', 'test_getClusterKVPairs.json'),
('clusters', 'test_getClusterKVPairs.py', 'negative_error_codes/test_getClusterKVPairsNeg404.json'),
('clusters', 'test_getClusterKVPairByName.py', 'test_getClusterKVPairByName.json'),
('clusters', 'test_getClusterKVPairByName.py', 'negative_error_codes/test_getClusterKVPairByNameNeg404.json'),
('clusters', 'test_queryKVPairsForCluster.py', 'test_queryKVPairsForCluster.json '),
('clusters', 'test_queryKVPairsForCluster.py', 'negative_error_codes/test_queryKVPairsForClusterNeg404.json'),
('logical_clouds', 'test_postLogicalClouds.py', 'test_postLogicalClouds.json'),
('logical_clouds', 'test_postLogicalClouds.py', 'test_postLogicalCloudsLc1.json'),
('logical_clouds', 'test_getLogicalClouds.py', 'test_getLogicalClouds.json'),
('logical_clouds', 'test_getLogicalCloudsByName.py', 'test_getLogicalCloudsByName.json'),
('logical_clouds', 'test_getLogicalCloudsByName.py', 'test_getLogicalCloudsLc1ByName.json'),
('logical_cloud_cluster_reference', 'test_postClusterReference.py', 'test_postClusterReference.json'),
('logical_cloud_cluster_reference', 'test_getClusterReferences.py', 'test_getClusterReferences.json'),
('logical_cloud_cluster_reference', 'test_getClusterReferenceByName.py', 'test_getClusterReferenceByName.json'),
('logical_clouds', 'test_instantiateLogicalClouds.py', 'test_instantiateLogicalClouds.json'),
('logical_clouds', 'test_instantiateLogicalClouds.py', 'negative_error_codes/test_instantiateLogicalCloudsNeg409.json'),
('logical_clouds', 'test_getLogicalClouds.py', 'test_getLogicalCloudsAfterInstantiate.json'),
('logical_clouds', 'test_getLogicalCloudsByName.py', 'test_getLogicalCloudsByNameAfterInstantiate.json'),
('composite_application', 'test_postCompositeApps.py', 'test_postCompositeApps.json'),
('composite_application', 'test_postCompositeApps.py', 'negative_error_codes/test_postCompositeAppsNeg400.json'),
('composite_application', 'test_postCompositeApps.py', 'negative_error_codes/test_postCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_postCompositeApps.py', 'negative_error_codes/test_postCompositeAppsNeg409.json'),
('composite_application', 'test_postCompositeAppsNeg422.py', 'negative_error_codes/test_postCompositeAppsNeg422.json'),
('composite_application', 'test_getCompositeApps.py', 'test_getCompositeApps.json'),
('composite_application', 'test_getCompositeApps.py', 'negative_error_codes/test_getCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_getCompositeAppsByName.py', 'test_getCompositeAppsByName.json'),
('composite_application', 'test_getCompositeAppsByName.py', 'negative_error_codes/test_getCompositeAppsByNameNeg404NoCompApp.json'),
('composite_application', 'test_getCompositeAppsByName.py', 'negative_error_codes/test_getCompositeAppsByNameNeg404NoProject.json'),
('composite_application', 'test_postAppCompositeApps.py', 'test_postAppCompositeApps.json'),
('composite_application', 'test_postAppCompositeApps.py', 'negative_error_codes/test_postAppCompositeAppsNeg400.json'),
('composite_application', 'test_postAppCompositeApps.py', 'negative_error_codes/test_postAppCompositeAppsNeg404NoCompApp.json'),
('composite_application', 'test_postAppCompositeApps.py', 'negative_error_codes/test_postAppCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_postAppCompositeApps.py', 'negative_error_codes/test_postAppCompositeAppsNeg409.json'),
('composite_application', 'test_postAppCompositeAppsNeg422.py', 'negative_error_codes/test_postAppCompositeAppsNeg422.json'),
('composite_application', 'test_getAppCompositeApps.py', 'test_getAppCompositeApps.json'),
('composite_application', 'test_getAppCompositeApps.py', 'negative_error_codes/test_getAppCompositeAppsNeg404NoCompApp.json'),
('composite_application', 'test_getAppCompositeApps.py', 'negative_error_codes/test_getAppCompositeAppsNeg404NoProject.json '),
('composite_application', 'test_getAppCompositeAppsByName.py', 'test_getAppCompositeAppsByName.json'),
('composite_application', 'test_getAppCompositeAppsByName.py', 'negative_error_codes/test_getAppCompositeAppsByNameNeg404NoCompApp.json'),
('composite_application', 'test_getAppCompositeAppsByName.py', 'negative_error_codes/test_getAppCompositeAppsByNameNeg404NoProject.json'),
('composite_application', 'test_getAppCompositeAppsByName.py', 'negative_error_codes/test_getAppCompositeAppsByNameNeg404NoApp.json'),
('composite_profile', 'test_postCompositeProfile.py', 'test_postCompositeProfile.json'),
('composite_profile', 'test_postCompositeProfile.py', 'negative_error_codes/test_postCompositeProfileNeg400.json'),
('composite_profile', 'test_postCompositeProfile.py', 'negative_error_codes/test_postCompositeProfileNeg404NoCompApp.json'),
('composite_profile', 'test_postCompositeProfile.py', 'negative_error_codes/test_postCompositeProfileNeg404NoProject.json'),
('composite_profile', 'test_postCompositeProfile.py', 'negative_error_codes/test_postCompositeProfileNeg409.json'),
('composite_profile', 'test_postCompositeProfileNeg422.py', 'negative_error_codes/test_postCompositeProfileNeg422.json'),
('composite_profile', 'test_getCompositeProfile.py', 'test_getCompositeProfile.json'),
('composite_profile', 'test_getCompositeProfile.py', 'negative_error_codes/test_getCompositeProfileNeg404NoCompApp.json'),
('composite_profile', 'test_getCompositeProfile.py', 'negative_error_codes/test_getCompositeProfileNeg404NoProject.json'),
('composite_profile', 'test_getCompositeProfileByName.py', 'test_getCompositeProfileByName.json'),
('composite_profile', 'test_getCompositeProfileByName.py', 'negative_error_codes/test_getCompositeProfileByNameNeg404NoCompApp.json'),
('composite_profile', 'test_getCompositeProfileByName.py', 'negative_error_codes/test_getCompositeProfileByNameNeg404NoProject.json'),
('composite_profile', 'test_getCompositeProfileByName.py', 'negative_error_codes/test_getCompositeProfileByNameNeg404NoCompProfile.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'test_postAppProfileCompositeProfile.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg400.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg404NoCompApp.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg404NoCompProfile.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg404NoProject.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg409.json'),
('composite_profile', 'test_postAppProfileCompositeProfileNeg422.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg422.json'),
('composite_profile', 'test_getAppProfileCompositeProfiles.py', 'test_getAppProfileCompositeProfile.json'),
('composite_profile', 'test_getAppProfileCompositeProfiles.py', 'negative_error_codes/test_getAppProfileCompositeProfileNeg404NoCompApp.json'),
('composite_profile', 'test_getAppProfileCompositeProfiles.py', 'negative_error_codes/test_getAppProfileCompositeProfileNeg404NoCompProfile.json'),
('composite_profile', 'test_getAppProfileCompositeProfiles.py', 'negative_error_codes/test_getAppProfileCompositeProfileNeg404NoProject.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'test_getAppProfileCompositeProfileByName.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'negative_error_codes/test_getAppProfileCompositeProfileByNameNeg404NoCompApp.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'negative_error_codes/test_getAppProfileCompositeProfileByNameNeg404NoCompProfile.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'negative_error_codes/test_getAppProfileCompositeProfileByNameNeg404NoAppProfile.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'negative_error_codes/test_getAppProfileCompositeProfileByNameNeg404NoProject.json'),
('composite_profile', 'test_queryProfileForApp.py', 'test_queryProfileForApp.json'),
('deployment_intent_group', 'test_postDeploymentIntentGroup.py', 'test_postDeploymentIntentGroup.json'),
('deployment_intent_group', 'test_getDeploymentIntentGroup.py', 'test_getDeploymentIntentGroup.json'),
('deployment_intent_group', 'test_getDeploymentIntentGroupByName.py', 'test_getDeploymentIntentGroupByName.json'),
('deployment_intent_group', 'test_postIntentDeploymentIntentGroup.py', 'test_postIntentDeploymentIntentGroup.json'),
('deployment_intent_group', 'test_getIntentDeploymentIntentGroup.py', 'test_getIntentDeploymentIntentGroup.json'),
('deployment_intent_group', 'test_getIntentDeploymentIntentGroupByName.py', 'test_getIntentDeploymentIntentGroupByName.json'),
('deployment_intent_group', 'test_queryIntentDeploymentIntentGroup.py', 'test_queryIntentDeploymentIntentGroup.json'),
('generic_placement_intent', 'test_postGenericPlacementIntent.py', 'test_postGenericPlacementIntent.json'),
('generic_placement_intent', 'test_postGenericPlacementIntent.py', 'negative_error_codes/test_postGenericPlacementIntentNeg400.json'),
('generic_placement_intent', 'test_postGenericPlacementIntent.py', 'mandatory_optional_inputs/test_postGenericPlacementIntent_EmptyMDName.json'),
('generic_placement_intent', 'test_postGenericPlacementIntent.py', 'mandatory_optional_inputs/test_postGenericPlacementIntent_NoMDName.json'),
('generic_placement_intent', 'test_postGenericPlacementIntent.py', 'negative_error_codes/test_postGenericPlacementIntentNeg404NoCompApp.json'),
('generic_placement_intent', 'test_postGenericPlacementIntent.py', 'negative_error_codes/test_postGenericPlacementIntentNeg404NoDeployIntentGroup.json'),
('generic_placement_intent', 'test_postGenericPlacementIntent.py', 'negative_error_codes/test_postGenericPlacementIntentNeg404NoProj.json'),
('generic_placement_intent', 'test_postGenericPlacementIntent.py', 'negative_error_codes/test_postGenericPlacementIntentNeg409.json'),
('generic_placement_intent', 'test_postGenericPlacementIntentNeg422.py', 'negative_error_codes/test_postGenericPlacementIntentNeg422.json'),
('generic_placement_intent', 'test_getGenericPlacementIntent.py', 'test_getGenericPlacementIntent.json'),
('generic_placement_intent', 'test_getGenericPlacementIntent.py', 'negative_error_codes/test_getGenericPlacementIntentNeg404NoCompApp.json'),
('generic_placement_intent', 'test_getGenericPlacementIntent.py', 'negative_error_codes/test_getGenericPlacementIntentNeg404NoDeploIntentGroup.json'),
('generic_placement_intent', 'test_getGenericPlacementIntent.py', 'negative_error_codes/test_getGenericPlacementIntentNeg404NoProj.json'),
('generic_placement_intent', 'test_getGenericPlacementIntentByName.py', 'test_getGenericPlacementIntentByName.json'),
('generic_placement_intent', 'test_getGenericPlacementIntentByName.py', 'negative_error_codes/test_getGenericPlacementIntentByNameNeg404NoCompApp.json'),
('generic_placement_intent', 'test_getGenericPlacementIntentByName.py', 'negative_error_codes/test_getGenericPlacementIntentByNameNeg404NoDeployIntent.json'),
('generic_placement_intent', 'test_getGenericPlacementIntentByName.py', 'negative_error_codes/test_getGenericPlacementIntentByNameNeg404NoGenericPlaceIntent.json'),
('generic_placement_intent', 'test_getGenericPlacementIntentByName.py', 'negative_error_codes/test_getGenericPlacementIntentByNameNeg404NoProj.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'test_postIntentGenericPlacementIntent.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'negative_error_codes/test_postIntentGenericPlacementIntentNeg400.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'mandatory_optional_inputs/test_postIntentGenericPlacementIntent_EmptyMDName.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'mandatory_optional_inputs/test_postIntentGenericPlacementIntent_NoMDName.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'negative_error_codes/test_postIntentGenericPlacementIntentNeg404NoCompApp.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'negative_error_codes/test_postIntentGenericPlacementIntentNeg404NoDeploIntentGroup.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'negative_error_codes/test_postIntentGenericPlacementIntentNeg404NoGenericPlaceIntent.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'negative_error_codes/test_postIntentGenericPlacementIntentNeg404NoProj.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntent.py', 'negative_error_codes/test_postIntentGenericPlacementIntentNeg409.json'),
('generic_placement_intent', 'test_postIntentGenericPlacementIntentNeg422.py', 'negative_error_codes/test_postIntentGenericPlacementIntentNeg422.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntent.py', 'test_getIntentGenericPlacementIntent.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntent.py', 'negative_error_codes/test_getIntentGenericPlacementIntentNeg404NoCompApp.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntent.py', 'negative_error_codes/test_getIntentGenericPlacementIntentNeg404NoDeployIntentGroup.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntent.py', 'negative_error_codes/test_getIntentGenericPlacementIntentNeg404NoProj.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntentByName.py', 'test_getIntentGenericPlacementIntentByName.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntentByName.py', 'negative_error_codes/test_getIntentGenericPlacementIntentByNameNeg404NoAppIntent.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntentByName.py', 'negative_error_codes/test_getIntentGenericPlacementIntentByNameNeg404NoCompApp.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntentByName.py', 'negative_error_codes/test_getIntentGenericPlacementIntentByNameNeg404NoDeployIntentGroup.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntentByName.py', 'negative_error_codes/test_getIntentGenericPlacementIntentByNameNeg404NoGenericPlaceIntent.json'),
('generic_placement_intent', 'test_getIntentGenericPlacementIntentByName.py', 'negative_error_codes/test_getIntentGenericPlacementIntentByNameNeg404NoProj.json'),
('generic_placement_intent', 'test_queryIntentForApp.py', 'test_queryIntentForApp.json'),
('generic_placement_intent', 'test_queryIntentForApp.py', 'negative_error_codes/test_queryIntentForAppNeg400.json'),
('generic_placement_intent', 'test_queryIntentForApp.py', 'negative_error_codes/test_queryIntentForAppNeg404NoAppIntent.json'),
('generic_placement_intent', 'test_queryIntentForApp.py', 'negative_error_codes/test_queryIntentForAppNeg404NoCompApp.json'),
('generic_placement_intent', 'test_queryIntentForApp.py', 'negative_error_codes/test_queryIntentForAppNeg404NoDeploymentIntentGroup.json'),
('generic_placement_intent', 'test_queryIntentForApp.py', 'negative_error_codes/test_queryIntentForAppNeg404NoGenericPlacementIntent.json'),
('generic_placement_intent', 'test_queryIntentForApp.py', 'negative_error_codes/test_queryIntentForAppNeg404NoProj.json'),
('generic_placement_intent', 'test_queryIntentForApp.py', 'negative_error_codes/test_queryIntentForAppNeg404NoSuchAppIntent.json'),
('deployment_lifecycle', 'test_instantiateDeployment.py', 'test_instantiateDeploymentBeforeApprove.json'),
('deployment_lifecycle', 'test_approveDeployment.py', 'test_approveDeployment.json'),
('deployment_lifecycle', 'test_approveDeployment.py', 'negative_error_codes/test_approveDeploymentNeg409.json'),
('deployment_lifecycle', 'test_terminateDeployment.py', 'test_terminateDeploymentBeforeInstantiate.json'),
('deployment_lifecycle', 'test_instantiateDeployment.py', 'test_instantiateDeployment.json'),
('deployment_lifecycle', 'test_instantiateDeployment.py', 'negative_error_codes/test_instantiateDeploymentNeg409.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'test_postTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'negative_error_codes/test_postTrafficControllerIntentNeg400.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postTrafficControllerIntent_EmptyMDName.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postTrafficControllerIntent_NoMDName.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'negative_error_codes/test_postTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'negative_error_codes/test_postTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'negative_error_codes/test_postTrafficControllerIntentNeg404NoDeploymentIntentGrp.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'negative_error_codes/test_postTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntent.py', 'negative_error_codes/test_postTrafficControllerIntentNeg409.json'),
('traffic_controller_intent', 'test_postTrafficControllerIntentNeg422.py', 'negative_error_codes/test_postTrafficControllerIntentNeg422.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntents.py', 'test_getTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntents.py', 'negative_error_codes/test_getTrafficControllerIntentNeg404NoCompApp.json '),
('traffic_controller_intent', 'test_getTrafficControllerIntents.py', 'negative_error_codes/test_getTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntents.py', 'negative_error_codes/test_getTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntents.py', 'negative_error_codes/test_getTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntentByName.py', 'test_getTrafficControllerIntentByName.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntentByName.py', 'negative_error_codes/test_getTrafficControllerIntentByNameNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntentByName.py', 'negative_error_codes/test_getTrafficControllerIntentByNameNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntentByName.py', 'negative_error_codes/test_getTrafficControllerIntentByNameNeg404NoDeployement.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntentByName.py', 'negative_error_codes/test_getTrafficControllerIntentByNameNeg404NoProject.json'),
('traffic_controller_intent', 'test_getTrafficControllerIntentByName.py', 'negative_error_codes/test_getTrafficControllerIntentByNameNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'test_postInboundServerIntentTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundServerIntentTrafficControllerIntentNeg400.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_EmptyApplication.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_EmptyMDName.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_EmptyProtocol.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_EmptyServiceName.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_InvalidProtocol.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_NegPort.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_NegPortNumber.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_NoApplication.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_NoMDName.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_NoPort.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_NoPortNumber.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_NoProtocol.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundServerIntentTrafficControllerIntent_NoServiceName.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundServerIntentTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundServerIntentTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundServerIntentTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundServerIntentTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundServerIntentTrafficControllerIntentNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundServerIntentTrafficControllerIntentNeg409.json'),
('traffic_controller_intent', 'test_postInboundServerIntentTrafficControllerIntentNeg422.py', 'negative_error_codes/test_postInboundServerIntentTrafficControllerIntentNeg422.json'),
('traffic_controller_intent', 'test_getInboundServerIntentsTrafficControllerIntent.py', 'test_getInboundServerIntentTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_getInboundServerIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_getInboundServerIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_getInboundServerIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_getInboundServerIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_getInboundServerIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_getInboundServerIntentTrafficControllerIntentByName.py', 'test_getInboundServerIntentTrafficControllerIntentByName.json'),
('traffic_controller_intent', 'test_getInboundServerIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentByNameNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_getInboundServerIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentByNameNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_getInboundServerIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentByNameNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_getInboundServerIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentByNameNeg404NoProject.json'),
('traffic_controller_intent', 'test_getInboundServerIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentByNameNeg404NoServerIntent.json'),
('traffic_controller_intent', 'test_getInboundServerIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundServerIntentTrafficControllerIntentByNameNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'test_postInboundClientIntentTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg400.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundClientIntentTrafficControllerIntent_EmptyApplication.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundClientIntentTrafficControllerIntent_EmptyMDName.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundClientIntentTrafficControllerIntent_EmptyServiceName.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundClientIntentTrafficControllerIntent_NoApplication.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundClientIntentTrafficControllerIntent_NoCidrs.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundClientIntentTrafficControllerIntent_NoMDName.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundClientIntentTrafficControllerIntent_NoNamespace.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'mandatory_optional_inputs/test_postInboundClientIntentTrafficControllerIntent_NoServiceName.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg404NoDeloymentIntent.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg404NoServerIntent.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg409.json'),
('traffic_controller_intent', 'test_postInboundClientIntentTrafficControllerIntentNeg422.py', 'negative_error_codes/test_postInboundClientIntentTrafficControllerIntentNeg422.json'),
('traffic_controller_intent', 'test_getInboundClientIntentsTrafficControllerIntent.py', 'test_getInboundClientIntentTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_getInboundClientIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_getInboundClientIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_getInboundClientIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_getInboundClientIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_getInboundClientIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentNeg404NoServerIntent.json'),
('traffic_controller_intent', 'test_getInboundClientIntentsTrafficControllerIntent.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_getInboundClientIntentTrafficControllerIntentByName.py', 'test_getInboundClientIntentTrafficControllerIntentByName.json'),
('traffic_controller_intent', 'test_getInboundClientIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentByNameNeg404NoClient.json'),
('traffic_controller_intent', 'test_getInboundClientIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentByNameNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_getInboundClientIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentByNameNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_getInboundClientIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentByNameNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_getInboundClientIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentByNameNeg404NoProject.json'),
('traffic_controller_intent', 'test_getInboundClientIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentByNameNeg404NoServerIntent.json'),
('traffic_controller_intent', 'test_getInboundClientIntentTrafficControllerIntentByName.py', 'negative_error_codes/test_getInboundClientIntentTrafficControllerIntentByNameNeg404NoTrafficIntent.json'),
('hpa_intent', 'test_postHPAIntent.py', 'test_postHPAIntent.json'),
('hpa_intent', 'test_postHPAIntent.py', 'negative_error_codes/test_postHPAIntentNeg400.json'),
('hpa_intent', 'test_postHPAIntent.py', 'mandatory_optional_inputs/test_postHPAIntent_EmptyAppName.json'),
('hpa_intent', 'test_postHPAIntent.py', 'mandatory_optional_inputs/test_postHPAIntent_EmptyMDName.json'),
('hpa_intent', 'test_postHPAIntent.py', 'mandatory_optional_inputs/test_postHPAIntent_InvalidAppName.json'),
('hpa_intent', 'test_postHPAIntent.py', 'mandatory_optional_inputs/test_postHPAIntent_NoAppName.json'),
('hpa_intent', 'test_postHPAIntent.py', 'mandatory_optional_inputs/test_postHPAIntent_NoMDName.json'),
('hpa_intent', 'test_postHPAIntent.py', 'negative_error_codes/test_postHPAIntentNeg404NoCompositeApp.json'),
('hpa_intent', 'test_postHPAIntent.py', 'negative_error_codes/test_postHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_postHPAIntent.py', 'negative_error_codes/test_postHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_postHPAIntent.py', 'negative_error_codes/test_postHPAIntentNeg409.json'),
('hpa_intent', 'test_postHPAIntentNeg422.py', 'negative_error_codes/test_postHPAIntentNeg422.json'),
('hpa_intent', 'test_getHPAIntents.py', 'test_getHPAIntents.json'),
('hpa_intent', 'test_getHPAIntents.py', 'negative_error_codes/test_getHPAIntentsNeg404NoCompositeApp.json'),
('hpa_intent', 'test_getHPAIntents.py', 'negative_error_codes/test_getHPAIntentsNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_getHPAIntents.py', 'negative_error_codes/test_getHPAIntentsNeg404NoProject.json'),
('hpa_intent', 'test_getHPAIntentByName.py', 'test_getHPAIntentByName.json'),
('hpa_intent', 'test_queryHPAIntent.py', 'test_queryHPAIntent.json'),
('hpa_intent', 'test_queryHPAIntent.py', 'negative_error_codes/test_queryHPAIntentNeg404NoCompApp.json '),
('hpa_intent', 'test_queryHPAIntent.py', 'negative_error_codes/test_queryHPAIntentNeg404NoDeploymentIntent.json'),
('hpa_intent', 'test_queryHPAIntent.py', 'negative_error_codes/test_queryHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_queryHPAIntent.py', 'negative_error_codes/test_queryHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'test_postHPAResourceConsumerHPAIntent.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_postHPAResourceConsumerHPAIntentNeg400.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'mandatory_optional_inputs/test_postHPAResourceConsumerHPAIntent_EmptyMDName.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'mandatory_optional_inputs/test_postHPAResourceConsumerHPAIntent_EmptySpecName.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'mandatory_optional_inputs/test_postHPAResourceConsumerHPAIntent_NoMDName.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'mandatory_optional_inputs/test_postHPAResourceConsumerHPAIntent_NoSpecName.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_postHPAResourceConsumerHPAIntentNeg404NoCompositeApp.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_postHPAResourceConsumerHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_postHPAResourceConsumerHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_postHPAResourceConsumerHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_postHPAResourceConsumerHPAIntentNeg409.json'),
('hpa_intent', 'test_postHPAResourceConsumerHPAIntentNeg422.py', 'negative_error_codes/test_postHPAResourceConsumerHPAIntentNeg422.json'),
('hpa_intent', 'test_getHPAResourceConsumerHPAIntent.py', 'test_getHPAResourceConsumerHPAIntent.json'),
('hpa_intent', 'test_getHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_getHPAResourceConsumerHPAIntentNeg404NoCompositeApp.json'),
('hpa_intent', 'test_getHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_getHPAResourceConsumerHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_getHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_getHPAResourceConsumerHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_getHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_getHPAResourceConsumerHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_getHPAResourceConsumerHPAIntentByName.py', 'test_getHPAResourceConsumerHPAIntentByName.json'),
('hpa_intent', 'test_queryHPAResourceConsumerHPAIntent.py', 'test_queryHPAResourceConsumerHPAIntent.json'),
('hpa_intent', 'test_queryHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_queryHPAResourceConsumerHPAIntentNeg404NoCompApp.json'),
('hpa_intent', 'test_queryHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_queryHPAResourceConsumerHPAIntentNeg404NoDeploymentIntent.json'),
('hpa_intent', 'test_queryHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_queryHPAResourceConsumerHPAIntentNeg404NoHPAConsumerIntent.json'),
('hpa_intent', 'test_queryHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_queryHPAResourceConsumerHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_queryHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_queryHPAResourceConsumerHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'test_postResourceHPAIntent.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'negative_error_codes/test_postResourceHPAIntentNeg400.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_EmptyAllocResName.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_EmptyNOnAllocResKey.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_EmptyNOnAllocResValue.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_NoAllocatable.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_NoAllocResName.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_NoAllocResRequest.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_NoNOnAllocResKey.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_NoNOnAllocResValue.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_NoResource.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'mandatory_optional_inputs/test_postResourceHPAIntent_ZeroAllocResRequest.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'negative_error_codes/test_postResourceHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'negative_error_codes/test_postResourceHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'negative_error_codes/test_postResourceHPAIntentNeg404NoHPAIntentConsumer.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'negative_error_codes/test_postResourceHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'negative_error_codes/test_postResourceHPAIntentNeg404NoCompositeApp.json'),
('hpa_intent', 'test_postResourceHPAIntent.py', 'negative_error_codes/test_postResourceHPAIntentNeg409.json'),
('hpa_intent', 'test_postResourceHPAIntentNeg422.py', 'negative_error_codes/test_postResourceHPAIntentNeg422.json'),
('hpa_intent', 'test_getResourceHPAIntent.py', 'test_getResourceHPAIntent.json'),
('hpa_intent', 'test_getResourceHPAIntent.py', 'negative_error_codes/test_getResourceHPAIntentNeg404NoCompositeApp.json'),
('hpa_intent', 'test_getResourceHPAIntent.py', 'negative_error_codes/test_getResourceHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_getResourceHPAIntent.py', 'negative_error_codes/test_getResourceHPAIntentNeg404NoHPAConsumerIntent.json'),
('hpa_intent', 'test_getResourceHPAIntent.py', 'negative_error_codes/test_getResourceHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_getResourceHPAIntent.py', 'negative_error_codes/test_getResourceHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_getResourceHPAIntentByName.py', 'test_getResourceHPAIntentByName.json'),
('hpa_intent', 'test_queryResourceHPAIntent.py', 'test_queryResourceHPAIntent.json'),
('hpa_intent', 'test_queryResourceHPAIntent.py', 'negative_error_codes/test_queryResourceHPAIntentNeg404NoCompApp.json'),
('hpa_intent', 'test_queryResourceHPAIntent.py', 'negative_error_codes/test_queryResourceHPAIntentNeg404NoDeploymentIntent.json'),
('hpa_intent', 'test_queryResourceHPAIntent.py', 'negative_error_codes/test_queryResourceHPAIntentNeg404NoHPAConsumerIntent.json'),
('hpa_intent', 'test_queryResourceHPAIntent.py', 'negative_error_codes/test_queryResourceHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_queryResourceHPAIntent.py', 'negative_error_codes/test_queryResourceHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_queryResourceHPAIntent.py', 'negative_error_codes/test_queryResourceHPAIntentNeg404NoResource.json'),
('logical_cloud_user_permissions', 'test_postUserPermissions.py', 'test_postUserPermissions.json'),
('logical_cloud_user_permissions', 'test_postUserPermissions.py', 'negative_error_codes/test_postUserPermissionsNeg400.json '),
('logical_cloud_user_permissions', 'test_getUserPermissions.py', 'test_getUserPermissions.json '),
('logical_cloud_user_permissions', 'test_getUserPermissions.py', 'negative_error_codes/test_getUserPermissionsNeg404NoProject.json '),
('logical_cloud_user_permissions', 'test_getUserPermissions.py', 'negative_error_codes/test_getUserPermissionsNeg404NoLogicalCloud.json '),
('logical_cloud_user_permissions', 'test_getUserPermissionsByName.py', 'test_getUserPermissionsByName.json '),
('logical_cloud_user_permissions', 'test_getUserPermissionsByName.py', 'negative_error_codes/test_getUserPermissionsByNameNeg404NoProject.json '),
('logical_cloud_user_permissions', 'test_getUserPermissionsByName.py', 'negative_error_codes/test_getUserPermissionsByNameNeg404NoLogicalCloud.json '),
('logical_cloud_user_permissions', 'test_getUserPermissionsByName.py', 'negative_error_codes/test_getUserPermissionsByNameNeg404NoUserPermission.json'),
('logical_cloud_cluster_quotas', 'test_postClusterQuotas.py', 'test_postClusterQuotas.json '),
('logical_cloud_cluster_quotas', 'test_postClusterQuotas.py', 'negative_error_codes/test_postClusterQuotasNeg400.json '),
('logical_cloud_cluster_quotas', 'test_getClusterQuotas.py ', 'test_getClusterQuotas.json'),
('logical_cloud_cluster_quotas', 'test_getClusterQuotas.py ', 'negative_error_codes/test_getClusterQuotasNeg404NoProject.json '),
('logical_cloud_cluster_quotas', 'test_getClusterQuotas.py ', 'negative_error_codes/test_getClusterQuotasNeg404NoLogicalCloud.json'),
('logical_cloud_cluster_quotas', 'test_getClustersQuotasByName.py', 'test_getClustersQuotasByName.json'),
('logical_cloud_cluster_quotas', 'test_getClustersQuotasByName.py', 'negative_error_codes/test_getClusterQuotasByNameNeg404NoProject.json'),
('logical_cloud_cluster_quotas', 'test_getClustersQuotasByName.py', 'negative_error_codes/test_getClusterQuotasByNameNeg404NoLogicalCloud.json'),
('logical_cloud_cluster_quotas', 'test_getClustersQuotasByName.py', 'negative_error_codes/test_getClusterQuotasByNameNeg404NoClusterQuotas.json'),
('clm_controller_registration','test_postClmControllers.py', 'test_postClmControllerRegistration.json'),
('clm_controller_registration', 'test_getClmControllers.py', 'test_getClmControllerRegistrations.json'),
('clm_controller_registration', 'test_getClmControllersByName.py', 'test_getClmControllerRegistrationByName.json'),
('deployment_lifecycle', 'test_statusDeployment.py', 'test_statusDeploymentAfterInstantiation.json '),
('deployment_lifecycle', 'test_statusDeployment.py', 'test_statusDeploymentAfterInstantiationApps.json'),
('deployment_lifecycle', 'test_statusDeployment.py', 'negative_error_codes/test_statusDeploymentAfterInstantiationNeg404NoApp.json'),
('deployment_lifecycle', 'test_statusDeployment.py', 'test_statusDeploymentAfterInstantiationClusters.json'),
('deployment_lifecycle', 'test_statusDeployment.py', 'negative_error_codes/test_statusDeploymentAfterInstantiationNeg404NoCluster.json'),
('deployment_lifecycle', 'test_statusDeployment.py', 'test_statusDeploymentAfterInstantiationResources.json'),
('deployment_lifecycle', 'test_statusDeployment.py', 'negative_error_codes/test_statusDeploymentAfterInstantiationNeg404NoResource.json'),
('deployment_lifecycle', 'test_terminateDeployment.py', 'test_terminateDeployment.json'),
('deployment_lifecycle', 'test_terminateDeployment.py', 'negative_error_codes/test_terminateDeploymentNeg409.json'),
('logical_clouds', 'test_terminateLogicalClouds.py', 'test_terminateLogicalClouds.json'),
('logical_clouds', 'test_terminateLogicalClouds.py', 'negative_error_codes/test_terminateLogicalCloudsNeg409.json'),
('logical_clouds', 'test_getLogicalClouds.py', 'test_getLogicalCloudsAfterTerminate.json'),
('logical_clouds', 'test_getLogicalCloudsByName.py', 'test_getLogicalCloudsByNameAfterTerminate.json'),
('deployment_lifecycle', 'test_statusDeployment.py', 'test_statusDeploymentAfterTermination.json'),


('logical_cloud_cluster_reference', 'test_deleteClusterReference.py', 'test_deleteClusterReference.json'),
('logical_cloud_user_permissions', 'test_deleteUserPermissions.py', 'test_deleteUserPermissions.json'),
('logical_cloud_user_permissions','test_deleteUserPermissions.py', 'negative_error_codes/test_deleteUserPermissionsNeg404NoProject.json'),
('logical_cloud_user_permissions','test_deleteUserPermissions.py', 'negative_error_codes/test_deleteUserPermissionsNeg404NoLogicalCloud.json'),
('logical_cloud_user_permissions','test_deleteUserPermissions.py', 'negative_error_codes/test_deleteUserPermissionsNeg404NoUser.json'),
('logical_cloud_cluster_quotas', 'test_deleteClusterQuotas.py', 'test_deleteClusterQuotas.json'),
('logical_cloud_cluster_quotas', 'test_deleteClusterQuotas.py', 'negative_error_codes/test_deleteClusterQuotasNeg404NoProject.json'),
('logical_cloud_cluster_quotas', 'test_deleteClusterQuotas.py', 'negative_error_codes/test_deleteClusterQuotasNeg404NoLogicalCloud.json'),
('logical_cloud_cluster_quotas', 'test_deleteClusterQuotas.py', 'negative_error_codes/test_deleteClusterQuotasNeg404NoClusterQuotas.json'),
('clusters', 'test_deleteClusterKVPair.py', 'test_deleteClusterKVPair.json'),
('clusters', 'test_deleteClusterKVPair.py', 'negative_error_codes/test_deleteClusterKVPairNeg404NoCluster.json'),
('clusters', 'test_deleteClusterKVPair.py', 'negative_error_codes/test_deleteClusterKVPairNeg404NoClusterProvider.json'),
('clusters', 'test_deleteClusterKVPair.py', 'negative_error_codes/test_deleteClusterKVPairNeg404NoKV.json'),
('clusters', 'test_deleteClusterLabel.py', 'test_deleteClusterLabel.json'),
('clusters', 'test_deleteClusterLabel.py', 'negative_error_codes/test_deleteClusterLabelNeg404NoCluster.json'),
('clusters', 'test_deleteClusterLabel.py', 'negative_error_codes/test_deleteClusterLabelNeg404NoClusterProvider.json'),
('clusters', 'test_deleteClusterLabel.py', 'negative_error_codes/test_deleteClusterLabelNeg404NoLabel.json'),
('clusters', 'test_deleteClusterByName.py', 'test_deleteClusterByName.json'),
('clusters', 'test_deleteClusterByName.py', 'negative_error_codes/test_deleteClusterByNameNeg404NoCluster.json'),
('clusters', 'test_deleteClusterByName.py', 'negative_error_codes/test_deleteClusterByNameNeg404NoClusterProvider.json'),
('cluster_provider', 'test_deleteClusterProviderByName.py', 'test_deleteClusterProviderByName.json'),
('cluster_provider', 'test_deleteClusterProviderByName.py', 'test_deleteClusterProviderByNameNeg404.json'),
('clm_controller_registration', 'test_deleteClmControllerByName.py', 'test_deleteClmControllerByName.json'),
('dtc_controllers', 'test_deleteDtcControllers.py', 'test_deleteDtcControllers.json'),
('controller_registration','test_deleteControllerByName.py', 'test_deleteControllerByName.json'),
('controller_registration','test_deleteControllerByName.py', 'test_deleteTrafficControllerByName.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'test_deleteResourceHPAIntent.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoCompApp.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoDeploymentIntentGrp.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoHPAConsumer.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoHPAResource.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'test_deleteHPAResourceConsumerHPAIntent.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoCompApp.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoHPAConsumer.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'test_deleteHPAIntent.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'negative_error_codes/test_deleteHPAIntentNeg404NoCompApp.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'negative_error_codes/test_deleteHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'negative_error_codes/test_deleteHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'negative_error_codes/test_deleteHPAIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'test_deleteInboundClientIntentTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoClientIntent.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoServerIntent.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'test_deleteInboundServerIntentTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoServerIntent.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'test_deleteTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoTrafficIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'test_deleteIntentGenericPlacementIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoAppIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoCompApp.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoDepIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoGenricPlaceIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoProj.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'test_deleteGenericPlacementIntent.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'negative_error_codes/test_deleteGenericPlacementIntentNeg404NoCompApp.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'negative_error_codes/test_deleteGenericPlacementIntentNeg404NoDepIntentGroup.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'negative_error_codes/test_deleteGenericPlacementIntentNeg404NoGenPlaceIntent.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'negative_error_codes/test_deleteGenericPlacementIntentNeg404NoProj.json'),
('deployment_intent_group', 'test_deleteIntentDeploymentIntentGroup.py', 'test_deleteIntentDeploymentIntentGroupName.json'),
('deployment_intent_group','test_deleteDeploymentIntentGroup.py', 'test_deleteDeploymentIntentGroupName.json'),
('composite_profile', 'test_deleteAppProfileCompositeProfile.py', 'test_deleteAppProfileCompositeProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoAppProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoCompApp.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoCompProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoProject.json'),
('composite_profile','test_deleteCompositeProfile.py', 'test_deleteCompositeProfile.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoCompApp.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoCompProfile.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoProject.json'),
('composite_application','test_deleteAppCompositeApps.py', 'test_deleteAppCompositeApps.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoApp.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoCompApp.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_deleteCompositeApps.py', 'test_deleteCompositeApps.json'),
('logical_clouds', 'test_deleteLogicalClouds.py', 'test_deleteLogicalClouds.json'),
('logical_clouds', 'test_deleteLogicalClouds.py', 'test_deleteLogicalCloudsLc1.json'),
('project', 'test_deleteProjectsByName.py', 'test_deleteProjectsByName.json'),
('project', 'test_deleteProjectsByName.py', 'negative_error_codes/test_deleteProjectsByNameNeg404.json')]



cleanup_test_list = [('deployment_lifecycle', 'test_terminateDeployment.py', 'test_terminateDeployment.json'),
('deployment_lifecycle', 'test_terminateDeployment.py', 'negative_error_codes/test_terminateDeploymentNeg409.json'),
('deployment_lifecycle', 'test_statusDeployment.py', 'test_statusDeploymentAfterTermination.json'),
('logical_clouds', 'test_terminateLogicalClouds.py', 'test_terminateLogicalClouds.json'),
('logical_clouds', 'test_terminateLogicalClouds.py', 'negative_error_codes/test_terminateLogicalCloudsNeg409.json'),
('logical_clouds', 'test_getLogicalClouds.py', 'test_getLogicalCloudsAfterTerminate.json'),
('logical_clouds', 'test_getLogicalCloudsByName.py', 'test_getLogicalCloudsByNameAfterTerminate.json'),
('logical_cloud_cluster_reference', 'test_deleteClusterReference.py', 'test_deleteClusterReference.json'),
('logical_cloud_user_permissions', 'test_deleteUserPermissions.py', 'test_deleteUserPermissions.json'),
('logical_cloud_user_permissions','test_deleteUserPermissions.py', 'negative_error_codes/test_deleteUserPermissionsNeg404NoProject.json'),
('logical_cloud_user_permissions','test_deleteUserPermissions.py', 'negative_error_codes/test_deleteUserPermissionsNeg404NoLogicalCloud.json'),
('logical_cloud_user_permissions','test_deleteUserPermissions.py', 'negative_error_codes/test_deleteUserPermissionsNeg404NoUser.json'),
('logical_cloud_cluster_quotas', 'test_deleteClusterQuotas.py', 'test_deleteClusterQuotas.json'),
('logical_cloud_cluster_quotas', 'test_deleteClusterQuotas.py', 'negative_error_codes/test_deleteClusterQuotasNeg404NoProject.json'),
('logical_cloud_cluster_quotas', 'test_deleteClusterQuotas.py', 'negative_error_codes/test_deleteClusterQuotasNeg404NoLogicalCloud.json'),
('logical_cloud_cluster_quotas', 'test_deleteClusterQuotas.py', 'negative_error_codes/test_deleteClusterQuotasNeg404NoClusterQuotas.json'),
('clusters', 'test_deleteClusterKVPair.py', 'test_deleteClusterKVPair.json'),
('clusters', 'test_deleteClusterKVPair.py', 'negative_error_codes/test_deleteClusterKVPairNeg404NoCluster.json'),
('clusters', 'test_deleteClusterKVPair.py', 'negative_error_codes/test_deleteClusterKVPairNeg404NoClusterProvider.json'),
('clusters', 'test_deleteClusterKVPair.py', 'negative_error_codes/test_deleteClusterKVPairNeg404NoKV.json'),
('clusters', 'test_deleteClusterLabel.py', 'test_deleteClusterLabel.json'),
('clusters', 'test_deleteClusterLabel.py', 'negative_error_codes/test_deleteClusterLabelNeg404NoCluster.json'),
('clusters', 'test_deleteClusterLabel.py', 'negative_error_codes/test_deleteClusterLabelNeg404NoClusterProvider.json'),
('clusters', 'test_deleteClusterLabel.py', 'negative_error_codes/test_deleteClusterLabelNeg404NoLabel.json'),
('clusters', 'test_deleteClusterByName.py', 'test_deleteClusterByName.json'),
('clusters', 'test_deleteClusterByName.py', 'negative_error_codes/test_deleteClusterByNameNeg404NoCluster.json'),
('clusters', 'test_deleteClusterByName.py', 'negative_error_codes/test_deleteClusterByNameNeg404NoClusterProvider.json'),
('cluster_provider', 'test_deleteClusterProviderByName.py', 'test_deleteClusterProviderByName.json'),
('cluster_provider', 'test_deleteClusterProviderByName.py', 'test_deleteClusterProviderByNameNeg404.json'),
('clm_controller_registration', 'test_deleteClmControllerByName.py', 'test_deleteClmControllerByName.json'),
('dtc_controllers', 'test_deleteDtcControllers.py', 'test_deleteDtcControllers.json'),
('controller_registration','test_deleteControllerByName.py', 'test_deleteControllerByName.json'),
('controller_registration','test_deleteControllerByName.py', 'test_deleteTrafficControllerByName.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'test_deleteResourceHPAIntent.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoCompApp.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoDeploymentIntentGrp.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoHPAConsumer.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoHPAResource.json'),
('hpa_intent', 'test_deleteResourceHPAIntent.py', 'negative_error_codes/test_deleteResourceHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'test_deleteHPAResourceConsumerHPAIntent.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoCompApp.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoHPAConsumer.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_deleteHPAResourceConsumerHPAIntent.py', 'negative_error_codes/test_deleteHPAResourceConsumerHPAIntentNeg404NoProject.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'test_deleteHPAIntent.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'negative_error_codes/test_deleteHPAIntentNeg404NoCompApp.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'negative_error_codes/test_deleteHPAIntentNeg404NoDeploymentIntentGroup.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'negative_error_codes/test_deleteHPAIntentNeg404NoHPAIntent.json'),
('hpa_intent', 'test_deleteHPAIntent.py', 'negative_error_codes/test_deleteHPAIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'test_deleteInboundClientIntentTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoClientIntent.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoServerIntent.json'),
('traffic_controller_intent', 'test_deleteInboundClientIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundClientIntentTrafficControllerIntentNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'test_deleteInboundServerIntentTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoServerIntent.json'),
('traffic_controller_intent', 'test_deleteInboundServerIntentTrafficControllerIntent.py', 'negative_error_codes/test_deleteInboundServerIntentTrafficControllerIntentNeg404NoTrafficIntent.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'test_deleteTrafficControllerIntent.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoCompApp.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoCompAppVer.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoDeploymentIntent.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoProject.json'),
('traffic_controller_intent', 'test_deleteTrafficControllerIntent.py', 'negative_error_codes/test_deleteTrafficControllerIntentNeg404NoTrafficIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'test_deleteIntentGenericPlacementIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoAppIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoCompApp.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoDepIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoGenricPlaceIntent.json'),
('generic_placement_intent', 'test_deleteIntentGenericPlacementIntent.py', 'negative_error_codes/test_deleteIntentGenericPlacementIntentNeg404NoProj.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'test_deleteGenericPlacementIntent.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'negative_error_codes/test_deleteGenericPlacementIntentNeg404NoCompApp.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'negative_error_codes/test_deleteGenericPlacementIntentNeg404NoDepIntentGroup.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'negative_error_codes/test_deleteGenericPlacementIntentNeg404NoGenPlaceIntent.json'),
('generic_placement_intent', 'test_deleteGenericPlacementIntent.py', 'negative_error_codes/test_deleteGenericPlacementIntentNeg404NoProj.json'),
('deployment_intent_group', 'test_deleteIntentDeploymentIntentGroup.py', 'test_deleteIntentDeploymentIntentGroupName.json'),
('deployment_intent_group','test_deleteDeploymentIntentGroup.py', 'test_deleteDeploymentIntentGroupName.json'),
('composite_profile', 'test_deleteAppProfileCompositeProfile.py', 'test_deleteAppProfileCompositeProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoAppProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoCompApp.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoCompProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoProject.json'),
('composite_profile','test_deleteCompositeProfile.py', 'test_deleteCompositeProfile.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoCompApp.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoCompProfile.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoProject.json'),
('composite_application','test_deleteAppCompositeApps.py', 'test_deleteAppCompositeApps.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoApp.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoCompApp.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_deleteCompositeApps.py', 'test_deleteCompositeApps.json'),
('logical_clouds', 'test_deleteLogicalClouds.py', 'test_deleteLogicalClouds.json'),
('logical_clouds', 'test_deleteLogicalClouds.py', 'test_deleteLogicalCloudsLc1.json'),
('project', 'test_deleteProjectsByName.py', 'test_deleteProjectsByName.json'),
('project', 'test_deleteProjectsByName.py', 'negative_error_codes/test_deleteProjectsByNameNeg404.json')]



cleanup_query_list = [('composite_profile', 'test_deleteAppProfileCompositeProfile.py', 'test_deleteAppProfileCompositeProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoAppProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoCompApp.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoCompProfile.json'),
('composite_profile','test_deleteAppProfileCompositeProfile.py', 'negative_error_codes/test_deleteAppProfileCompositeProfileNeg404NoProject.json'),
('composite_profile','test_deleteCompositeProfile.py', 'test_deleteCompositeProfile.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoCompApp.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoCompProfile.json'),
('composite_profile','test_deleteCompositeProfile.py', 'negative_error_codes/test_deleteCompositeProfileNeg404NoProject.json'),
('composite_application','test_deleteAppCompositeApps.py', 'test_deleteAppCompositeApps.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoApp.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoCompApp.json'),
('composite_application','test_deleteAppCompositeApps.py', 'negative_error_codes/test_deleteAppCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_deleteCompositeApps.py', 'test_deleteCompositeApps.json'),
('project', 'test_deleteProjectsByName.py', 'test_deleteProjectsByName.json'),
('project', 'test_deleteProjectsByName.py', 'negative_error_codes/test_deleteProjectsByNameNeg404.json')]

test_query_list = [('project', 'test_postProjects.py', 'test_postProjects.json'),
('project','test_postProjects.py', 'negative_error_codes/test_postProjectsNeg400.json'),
('project', 'test_postProjects.py', 'negative_error_codes/test_postProjectsNeg404.json'),
('project', 'test_postProjects.py', 'negative_error_codes/test_postProjectsNeg409.json'),
('project', 'test_postProjectsNeg422.py', 'negative_error_codes/test_postProjectsNeg422.json'),
('project', 'test_getProjects.py', 'test_getProjects.json'),
('project', 'test_getProjects.py', 'negative_error_codes/test_getProjectsNeg404.json'),
('project', 'test_getProjectsByName.py', 'test_getProjectsByName.json'),
('project', 'test_getProjectsByName.py', 'negative_error_codes/test_getProjectsByNameNeg404.json'),
('composite_application', 'test_postCompositeApps.py', 'test_postCompositeApps.json'),
('composite_application', 'test_postCompositeApps.py', 'negative_error_codes/test_postCompositeAppsNeg400.json'),
('composite_application', 'test_postCompositeApps.py', 'negative_error_codes/test_postCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_postCompositeApps.py', 'negative_error_codes/test_postCompositeAppsNeg409.json'),
('composite_application', 'test_postCompositeAppsNeg422.py', 'negative_error_codes/test_postCompositeAppsNeg422.json'),
('composite_application', 'test_getCompositeApps.py', 'test_getCompositeApps.json'),
('composite_application', 'test_getCompositeApps.py', 'negative_error_codes/test_getCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_getCompositeAppsByName.py', 'test_getCompositeAppsByName.json'),
('composite_application', 'test_getCompositeAppsByName.py', 'negative_error_codes/test_getCompositeAppsByNameNeg404NoCompApp.json'),
('composite_application', 'test_getCompositeAppsByName.py', 'negative_error_codes/test_getCompositeAppsByNameNeg404NoProject.json'),
('composite_application', 'test_postAppCompositeApps.py', 'test_postAppCompositeApps.json'),
('composite_application', 'test_postAppCompositeApps.py', 'negative_error_codes/test_postAppCompositeAppsNeg400.json'),
('composite_application', 'test_postAppCompositeApps.py', 'negative_error_codes/test_postAppCompositeAppsNeg404NoCompApp.json'),
('composite_application', 'test_postAppCompositeApps.py', 'negative_error_codes/test_postAppCompositeAppsNeg404NoProject.json'),
('composite_application', 'test_postAppCompositeApps.py', 'negative_error_codes/test_postAppCompositeAppsNeg409.json'),
('composite_application', 'test_postAppCompositeAppsNeg422.py', 'negative_error_codes/test_postAppCompositeAppsNeg422.json'),
('composite_application', 'test_getAppCompositeApps.py', 'test_getAppCompositeApps.json'),
('composite_application', 'test_getAppCompositeApps.py', 'negative_error_codes/test_getAppCompositeAppsNeg404NoCompApp.json'),
('composite_application', 'test_getAppCompositeApps.py', 'negative_error_codes/test_getAppCompositeAppsNeg404NoProject.json '),
('composite_application', 'test_getAppCompositeAppsByName.py', 'test_getAppCompositeAppsByName.json'),
('composite_application', 'test_getAppCompositeAppsByName.py', 'negative_error_codes/test_getAppCompositeAppsByNameNeg404NoCompApp.json'),
('composite_application', 'test_getAppCompositeAppsByName.py', 'negative_error_codes/test_getAppCompositeAppsByNameNeg404NoProject.json'),
('composite_application', 'test_getAppCompositeAppsByName.py', 'negative_error_codes/test_getAppCompositeAppsByNameNeg404NoApp.json'),
('composite_profile', 'test_postCompositeProfile.py', 'test_postCompositeProfile.json'),
('composite_profile', 'test_postCompositeProfile.py', 'negative_error_codes/test_postCompositeProfileNeg400.json'),
('composite_profile', 'test_postCompositeProfile.py', 'negative_error_codes/test_postCompositeProfileNeg404NoCompApp.json'),
('composite_profile', 'test_postCompositeProfile.py', 'negative_error_codes/test_postCompositeProfileNeg404NoProject.json'),
('composite_profile', 'test_postCompositeProfile.py', 'negative_error_codes/test_postCompositeProfileNeg409.json'),
('composite_profile', 'test_postCompositeProfileNeg422.py', 'negative_error_codes/test_postCompositeProfileNeg422.json'),
('composite_profile', 'test_getCompositeProfile.py', 'test_getCompositeProfile.json'),
('composite_profile', 'test_getCompositeProfile.py', 'negative_error_codes/test_getCompositeProfileNeg404NoCompApp.json'),
('composite_profile', 'test_getCompositeProfile.py', 'negative_error_codes/test_getCompositeProfileNeg404NoProject.json'),
('composite_profile', 'test_getCompositeProfileByName.py', 'test_getCompositeProfileByName.json'),
('composite_profile', 'test_getCompositeProfileByName.py', 'negative_error_codes/test_getCompositeProfileByNameNeg404NoCompApp.json'),
('composite_profile', 'test_getCompositeProfileByName.py', 'negative_error_codes/test_getCompositeProfileByNameNeg404NoProject.json'),
('composite_profile', 'test_getCompositeProfileByName.py', 'negative_error_codes/test_getCompositeProfileByNameNeg404NoCompProfile.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'test_postAppProfileCompositeProfile.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg400.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg404NoCompApp.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg404NoCompProfile.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg404NoProject.json'),
('composite_profile', 'test_postAppProfileCompositeProfile.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg409.json'),
('composite_profile', 'test_postAppProfileCompositeProfileNeg422.py', 'negative_error_codes/test_postAppProfileCompositeProfileNeg422.json'),
('composite_profile', 'test_getAppProfileCompositeProfiles.py', 'test_getAppProfileCompositeProfile.json'),
('composite_profile', 'test_getAppProfileCompositeProfiles.py', 'negative_error_codes/test_getAppProfileCompositeProfileNeg404NoCompApp.json'),
('composite_profile', 'test_getAppProfileCompositeProfiles.py', 'negative_error_codes/test_getAppProfileCompositeProfileNeg404NoCompProfile.json'),
('composite_profile', 'test_getAppProfileCompositeProfiles.py', 'negative_error_codes/test_getAppProfileCompositeProfileNeg404NoProject.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'test_getAppProfileCompositeProfileByName.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'negative_error_codes/test_getAppProfileCompositeProfileByNameNeg404NoCompApp.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'negative_error_codes/test_getAppProfileCompositeProfileByNameNeg404NoCompProfile.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'negative_error_codes/test_getAppProfileCompositeProfileByNameNeg404NoAppProfile.json'),
('composite_profile', 'test_getAppProfileCompositeProfileByName.py', 'negative_error_codes/test_getAppProfileCompositeProfileByNameNeg404NoProject.json'),
('composite_profile', 'test_queryProfileForApp.py', 'test_queryProfileForApp.json')]